version: "3"

services:
  web:
    image: local/rmac/web
    build:
      context: ../..
      dockerfile: .cicd/sql-ledger/build/web/Dockerfile
    environment:
      - MOJO_REVERSE_PROXY=1
    networks:
      - traefik
      - private
    labels:
      traefik.enable: true
      traefik.docker.network: traefik
      traefik.frontend.rule: "Host:${LEDGER_HOST};PathPrefixStrip:${LEDGER_PATH_PREFIX}"
      traefik.port: 80
      traefik.frontend.redirect.entryPoint: https
    volumes:
      - ${LEDGER_DUMP_DIRECTORY}:/dumps:ro
      - ${LEDGER_SETUP_CONFIG}:/ledgersetup.yml:ro
    restart: unless-stopped
    depends_on:
      - db
    

  db:
    image: local/rmac/db
    build:
      context: build/db
    environment:
      - POSTGRES_PASSWORD=secret
    networks:
      - private
    volumes:
      - data:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  traefik:
    external: true
  private:

volumes:
  data:
