#!/bin/bash

if test -z "$LEDGER_PORT"; then
    echo "Environment not set up" 1>&2
    exit 1
fi


case $1 in
    up)
	docker-compose -f local-development.yml up -d --build
	;;
    down)
	docker-compose -f local-development.yml down
	;;
    init)
	shift
	docker-compose -f local-development.yml exec \
		       -T -u $LEDGER_APACHE_RUN_USER web ledgersetup.pl $1
	;;
    query)
	shift
	docker-compose -f local-development.yml exec \
		       -T -u $LEDGER_APACHE_RUN_USER web ledgerquery.pl "$@"
	;;
    *)
	cat <<EOF 1>&2 
Usage: $0 COMMAND

Where COMMAND is one of:
    up
    down
    init <ID>
    query <USERNAME> <YAML/KEY> [<BIND_PARAMS>...]
EOF

	exit 1
	;;
esac
