#!/bin/bash

if test -z "$LEDGER_PORT"; then
    echo "Environment not set up" 1>&2
    exit 1
fi


case $1 in
    up)
	docker-compose -f local-development.yml up -d --build
	;;
    down)
	docker-compose -f local-development.yml down
	;;
    init)
	docker-compose -f local-development.yml exec \
		       -T -u $LEDGER_APACHE_RUN_USER web ledgersetup.pl $2
	;;
    *)
	echo "Usage: $0 {up|down|init <ID>}" 1>&2
	exit 1
	;;
esac
