version: "3"

services:
  web:
    image: local/rmac/web
    build:
      context: build/web
      args:
        RESOURCE_DIR: .
        LEDGER_APACHE_RUN_USER:    ${LEDGER_APACHE_RUN_USER}
        LEDGER_APACHE_RUN_USERID:  ${LEDGER_APACHE_RUN_USERID}
        LEDGER_APACHE_RUN_GROUP:   ${LEDGER_APACHE_RUN_GROUP}
        LEDGER_APACHE_RUN_GROUPID: ${LEDGER_APACHE_RUN_GROUPID}

    ports:
      - ${LEDGER_PORT}:80
    volumes:
      - ../..:/srv/www/sql-ledger
      - ${LEDGER_DUMP_DIRECTORY}:/dumps:ro
      - ${LEDGER_SETUP_CONFIG}:/ledgersetup.yml:ro
    depends_on:
      - db
    
  db:
    image: local/rmac/db
    build:
      context: build/db
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
