version: "3"

services:
  web:
    environment:
      LEDGER_POSTGRES_USER: ${LEDGER_POSTGRES_USER:-sql-ledger}
    volumes:
      - ${LEDGER_DUMP_PATH}:/ledgersetup/dumps:ro
      - ${LEDGER_CONFIG_PATH}:/ledgersetup/configs:ro
  
  db:
    image: local/rmac/db
    build:
      context: build/db
    networks:
      - private
    volumes:
      - data:/var/lib/postgresql/data


volumes:
  data:
