version: "3"

services:
  web:
    build:
      args:
        BUILD_ENV: local
        LEDGER_APACHE_RUN_USER:    ${LEDGER_APACHE_RUN_USER}
        LEDGER_APACHE_RUN_USERID:  ${LEDGER_APACHE_RUN_USERID}
        LEDGER_APACHE_RUN_GROUP:   ${LEDGER_APACHE_RUN_GROUP}
        LEDGER_APACHE_RUN_GROUPID: ${LEDGER_APACHE_RUN_GROUPID}
    ports:
      - ${LEDGER_PORT}:80
    networks:
      - private
    volumes:
      - ../..:/srv/www/sql-ledger

networks:
  private:
